ARG BASE_IMAGE=debian:trixie
FROM ${BASE_IMAGE}

ARG BASE_FAMILY=debian
ARG VARIANT=pqc

COPY docker/common/generate-cert.sh /usr/local/bin/generate-cert.sh
COPY docker/nginx/setup.sh /usr/local/bin/setup-nginx.sh

RUN chmod +x /usr/local/bin/generate-cert.sh /usr/local/bin/setup-nginx.sh \
 && /usr/local/bin/setup-nginx.sh "${BASE_FAMILY}" "${VARIANT}"

EXPOSE 80 443

CMD ["sh", "-c", "nginx -g 'daemon off;'"]
